// src/pages/Quiz.js
import React, { useEffect, useState } from "react";
import Confetti from "react-confetti";
import { useWindowSize } from "react-use";
import { motion } from "framer-motion";
import "../styles/HobbyQuiz.css";

const API_BASE_URL = process.env.REACT_APP_API_BASE_URL;

function Quiz() {
  const [quiz, setQuiz] = useState(null);
  const [currentIndex, setCurrentIndex] = useState(0);
  const [answers, setAnswers] = useState([]);
  const [loading, setLoading] = useState(true);
  const [evaluating, setEvaluating] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState("");
  const [darkMode, setDarkMode] = useState(false);

  const { width, height } = useWindowSize();

  useEffect(() => {
    async function fetchQuiz() {
      try {
        const res = await fetch(`${API_BASE_URL}/quizzes/1`);
        if (!res.ok) throw new Error("Failed to load quiz");
        const data = await res.json();
        setQuiz(data);
      } catch (err) {
        setError("Unable to load quiz questions.");
      } finally {
        setLoading(false);
      }
    }
    fetchQuiz();
  }, []);

  const handleAnswerClick = (question_id, option_id) => {
    const newAnswers = [...answers, { question_id, selected_option_id: option_id }];
    const nextIndex = currentIndex + 1;

    if (quiz && nextIndex < quiz.questions.length) {
      setAnswers(newAnswers);
      setCurrentIndex(nextIndex);
    } else {
      submitForEvaluation(newAnswers);
    }
  };

  const submitForEvaluation = async (answersArray) => {
    setEvaluating(true);
    setError("");

    try {
      const res = await fetch(`${API_BASE_URL}/quizzes/1/evaluate`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ user_id: 1, answers: answersArray }),
      });

      if (!res.ok) {
        const errorText = await res.text();
        console.error("API Error Response:", errorText);
        throw new Error(`API error: ${res.status}`);
      }

      const data = await res.json();
      if (!res.ok) throw new Error(data?.error || "AI evaluation failed");

      setResult(data.ai_result);

    } catch (err) {
      console.error("Evaluation Error:", err);
      setError(err.message || "Evaluation error");
    } finally {
      setEvaluating(false);
    }
  };

  const saveResultToDB = async () => {
    await fetch(`${API_BASE_URL}/quizzes/save-result`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        user_id: 1,
        personality_type: result.personality_type,
        personality_summary: result.personality_summary,
        strengths: result.strengths,
        suggested_hobbies: result.suggested_hobbies || result.recommended_hobbies,
        reasons: result.reasons,
      }),
    });
    alert("Result saved to profile!");
  };

  if (loading) return <div className="quiz-loading">Loading quiz...</div>;

  if (error && !result) return <div className="quiz-page">{error}</div>;

  if (result) {
    return (
      <motion.div
        className={`quiz-page result-mode ${darkMode ? "dark-mode" : ""}`}
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
      >
        <Confetti width={width} height={height} recycle={false} numberOfPieces={250} />

        <motion.div
          className="quiz-result-card"
          initial={{ scale: 0.85 }}
          animate={{ scale: 1 }}
          transition={{ type: "spring", stiffness: 120 }}
        >
          <button className="dark-mode-toggle" onClick={() => setDarkMode(!darkMode)}>
            {darkMode ? "☀️ Light Mode" : "🌙 Dark Mode"}
          </button>

          <h2 className="quiz-result-title">{result.personality_type} 🎉</h2>

          <p className="ai-source-label">
            Generated by <strong>Gemini AI</strong> 🤖 • {new Date().toLocaleString()}
          </p>

          <p className="quiz-result-summary">
            {result.personality_summary?.replace(/\(Scores.*\)/, "")}
          </p>

          <h3 className="quiz-section-heading">🌟 Your Strengths</h3>
          <ul className="quiz-hobby-list">
            {(result.strengths || []).map((s, idx) => (
              <li key={idx} className="quiz-hobby-item">✨ {s}</li>
            ))}
          </ul>

          <h3 className="quiz-section-heading">🎯 Suggested Hobbies</h3>
          <ul className="quiz-hobby-list">
            {(result.suggested_hobbies || result.recommended_hobbies || []).map((item, idx) => (
              <li key={idx} className="quiz-hobby-item">
                🏆 {typeof item === "string" ? item : item.hobby}
              </li>
            ))}
          </ul>

          <h3 className="quiz-section-heading">💡 Why These Fit You</h3>
          <ul className="quiz-hobby-list">
            {(result.reasons || result.hobby_reasons || result.recommended_hobbies || []).map((item, idx) => (
              <li key={idx} className="quiz-hobby-item">
                • {typeof item === "string" ? item : item.reason}
              </li>
            ))}
          </ul>

          <button className="quiz-save-button" onClick={saveResultToDB}>
            Save Result 💾
          </button>

          <button className="quiz-share-button" onClick={() => window.print()}>
            Share Result 📤
          </button>

          <button
            className="quiz-retake-button"
            onClick={() => {
              setResult(null);
              setAnswers([]);
              setCurrentIndex(0);
            }}
          >
            Retake Quiz 🔁
          </button>
        </motion.div>
      </motion.div>
    );
  }

  const currentQuestion = quiz.questions[currentIndex];
  const total = quiz.questions.length;
  const progressPercent = Math.round(((currentIndex + 1) / total) * 100);

  return (
    <div className={`quiz-page ${darkMode ? "dark-mode" : ""}`}>
      <motion.div
        className="quiz-card"
        initial={{ opacity: 0, y: 15 }}
        animate={{ opacity: 1, y: 0 }}
      >
        <button className="dark-mode-toggle" onClick={() => setDarkMode(!darkMode)}>
          {darkMode ? "☀️" : "🌙"}
        </button>

        <div className="quiz-header-row">
          <span className="quiz-pill">Hobby Matcher</span>
          <span className="quiz-progress-label">
            Question {currentIndex + 1} of {total}
          </span>
        </div>

        <div className="quiz-progress-bar">
          <motion.div
            className="quiz-progress-fill"
            animate={{ width: `${progressPercent}%` }}
          />
        </div>

        <h2 className="quiz-question-text">{currentQuestion.question_text}</h2>

        <div className="quiz-options">
          {currentQuestion.options.map((opt) => (
            <motion.button
              key={opt.option_id}
              className="quiz-option-btn"
              whileTap={{ scale: 0.95 }}
              onClick={() => handleAnswerClick(currentQuestion.question_id, opt.option_id)}
              disabled={evaluating}
            >
              {opt.option_text}
            </motion.button>
          ))}
        </div>

        {evaluating && (
          <motion.p
            className="quiz-status-text"
            animate={{ opacity: [0, 1, 0] }}
            transition={{ duration: 1.5, repeat: Infinity }}
          >
            Evaluating with AI... 🔄
          </motion.p>
        )}
      </motion.div>
    </div>
  );
}

export default Quiz;
